services:
  - type: web
    name: roodle
    runtime: image
    image:
      url: ghcr.io/rtfpessoa/roodle:latest
    region: frankfurt
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: OAUTH2_GOOGLE_CREDENTIALS_FILE
        value: /etc/secrets/clientid.google.json
      - key: DATABASE_URL
        sync: false
      - key: COOKIE_SECRET
        sync: false
      - key: DD_API_KEY
        sync: false
