name: api

on:
  push:
    paths:
      - .github/workflows/api.yml
      - modules/api/**
  pull_request:
    paths:
      - .github/workflows/api.yml
      - modules/api/**
  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: modules/api
    strategy:
      matrix:
        go-version: ['1.20']

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: modules/api/go.sum
      - name: go generate
        run: go generate -v ./...
      - name: go build
        run: go build -v ./...
      - name: go test
        run: go test -v ./...
